sudo: true
dist: trusty
language: cpp
before_install:
  - cat /etc/os-release
  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/ /' >/tmp/qwtplot3d.list 
  - sudo mv /tmp/qwtplot3d.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libgsl0-dev
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y pyqt5-dev
  - sudo apt-get install -y python3-pyqt5
  - sudo apt-get install -y libqwtplot3d-qt5-dev
  - sudo apt-get install -y libqwt5-qt5-dev
  - sudo apt-get install -y libqt5svg5-dev
  - sudo apt-get install -y qttools5-dev
  - sudo apt-get install -y qtbase5-dev
  - sudo apt-get install -y qt5-default
  - sudo apt-get install -y libqt5opengl5-dev
  - sudo apt-get install -y libmuparser
  - sudo apt-get install -y libmuparser-dev
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y xvfb
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y libunittest++-dev
  - sudo apt-get install -y libboost-regex-dev
script: 
  # required to avoid picking up a bodgy python interpreter
  - export PATH=/usr/bin:$PATH
  - export PYTHON=python3
  - qmake CONFIG+=aegis
  - make
  - Xvfb :0 &
  - export DISPLAY=:0
  - export TRAVIS=1
  - for i in test/00/*; do if sh $i; then true; else exit 1; fi; done
