name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:

    runs-on: ubuntu-${{ matrix.ubuntu_ver }}

    strategy:
      fail-fast: false
      matrix:
        ubuntu_ver: [18.04, 20.04]

    name: ubuntu-${{ matrix.ubuntu_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install prerequisties
        run: |
          wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_${{ matrix.ubuntu_ver }}/Release.key
          sudo apt-key add - < Release.key
          sudo add-apt-repository -y \
            'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_${{ matrix.ubuntu_ver }}/ /'
          sudo apt install -y --no-install-recommends \
            qtbase5-dev \
            qttools5-dev \
            libqt5svg5-dev \
            libqt5opengl5-dev \
            libmuparser-dev \
            libgsl-dev \
            libqwt5-qt5-dev \
            libqwtplot3d-qt5-dev \
            pyqt5-dev \
            python3-pyqt5 \
            libunittest++-dev \
            libboost-regex-dev \
            python3-numpy \
            xvfb

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -DSEARCH_FOR_UPDATES=OFF -DDOWNLOAD_LINKS=OFF -DORIGIN_IMPORT=ON

      - name: Building
        run: |
          make -j$(nproc) -C build

      - name: Testing
        run: |
          cd build
          xvfb-run ctest --output-on-failure

  MSVC:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        qt_ver: [5.12.10, 5.15.2]

    name: MSVC_Qt_${{ matrix.qt_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.qt_ver }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - uses: lukka/run-vcpkg@v6
        with:
          vcpkgGitCommitId: 50ea8c0ab7aca3bb9245bba7fc877ad2f2a4464c
          setupOnly: true
      - name: Install VCPKG packages
        run: |
          Add-Content ${{ env.VCPKG_ROOT }}\triplets\x64-windows.cmake "set(VCPKG_BUILD_TYPE release)" 
          ${{ env.VCPKG_ROOT }}\vcpkg install zlib gsl muparser opengl gl2ps boost-regex unittest-cpp `
            --triplet x64-windows

      - name: Download Qwt5 and QwtPlot3D
        run: |
          git submodule update --init --recursive

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake `
            -DORIGIN_IMPORT=ON

      - uses: microsoft/setup-msbuild@v1.0.2
      - name: Building
        run: |
          MSBuild -maxCpuCount -property:Configuration=Release build\scidavis.sln

      - name: Testing
        run: |
          cd build
          ctest -C Release --output-on-failure

  MinGW-w64:

    runs-on: windows-latest

    name: MinGW-w64

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install MinGW-w64 packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            wget
            patch
            git
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-muparser
            mingw-w64-x86_64-gsl
            mingw-w64-x86_64-gl2ps
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-unittest-cpp
            mingw-w64-x86_64-sip
            mingw-w64-x86_64-python-pyqt5
            mingw-w64-x86_64-python-numpy

      - name: Download Qwt5 and QwtPlot3D
        run: |
          git submodule update --init --recursive

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -G"MSYS Makefiles" -DORIGIN_IMPORT=ON

      - name: Building
        run: |
          make -C build -j$(nproc)

      - name: Testing
        run: |
          cd build
          ctest --output-on-failure
